apiVersion: v2
appVersion: v2.3.4
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool for Kubernetes.
name: argo-cd
version: 4.8.0
home: https://github.com/argoproj/argo-helm
icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
keywords:
  - argoproj
  - argocd
  - gitops
maintainers:
  - name: alexec
  - name: alexmt
  - name: jessesuen
  - name: seanson
annotations:
  artifacthub.io/changes: |
    - "[Changed]: Can specify log format for Argo-CD Notifications component"
